export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const LOAD_INGREDIENT_SUCCESSFUL = 'LOAD_INGREDIENT_SUCCESSFUL';
export const LOAD_INGREDIENT_FAIL = 'LOAD_INGREDIENT_FAIL';

export const PLACE_ORDER_SUCCESSFUL = 'PLACE_ORDER_SUCCESSFUL';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';
export const PLACE_ORDER_START = 'PLACE_ORDER_START';
export const PLACE_ORDER_INIT = 'PLACE_ORDER_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';   

export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';